# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget RmlCore RmlDebugger)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target RmlCore
add_library(RmlCore SHARED IMPORTED)

set_target_properties(RmlCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "E:/GitHub/RmlUi/Ext/freetype-windows-binaries-2.10.4/win32/freetype.lib"
)

# Create imported target RmlDebugger
add_library(RmlDebugger SHARED IMPORTED)

set_target_properties(RmlDebugger PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "RmlCore"
)

# Import target "RmlCore" for configuration "Debug"
set_property(TARGET RmlCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RmlCore PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/GitHub/RmlUi/vs/Debug/RmlCore.lib"
  IMPORTED_LOCATION_DEBUG "E:/GitHub/RmlUi/vs/Debug/RmlCore.dll"
  )

# Import target "RmlDebugger" for configuration "Debug"
set_property(TARGET RmlDebugger APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(RmlDebugger PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/GitHub/RmlUi/vs/Debug/RmlDebugger.lib"
  IMPORTED_LOCATION_DEBUG "E:/GitHub/RmlUi/vs/Debug/RmlDebugger.dll"
  )

# Import target "RmlCore" for configuration "Release"
set_property(TARGET RmlCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(RmlCore PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/GitHub/RmlUi/vs/Release/RmlCore.lib"
  IMPORTED_LOCATION_RELEASE "E:/GitHub/RmlUi/vs/Release/RmlCore.dll"
  )

# Import target "RmlDebugger" for configuration "Release"
set_property(TARGET RmlDebugger APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(RmlDebugger PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/GitHub/RmlUi/vs/Release/RmlDebugger.lib"
  IMPORTED_LOCATION_RELEASE "E:/GitHub/RmlUi/vs/Release/RmlDebugger.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
